[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
voyager = "0.2"
reqwest = "0.11"
futures = "0.3"
anyhow = "1.0"
csv = "1"
tokio = { version = "1", features = ["full"] }